platform :ios, '9.0'
use_frameworks!

target 'ImageSelector_Example' do
    
  pod 'ImageSelector', :path => '../'
  pod 'PermissionsService/Camera', :git => 'https://github.com/lemberg/ios-permissions-service', :branch => 'feature/new_logic'
  pod 'PermissionsService/Gallery', :git => 'https://github.com/lemberg/ios-permissions-service', :branch => 'feature/new_logic'

end
